[package]
name = "rustblocks"
version = "0.1.0"
authors = ["Andrea Tomasi(treere)"]
edition = "2018"

[dependencies]
amethyst = {"version" ="0.10.0" ,"features"=["nightly"]}
serde = "*"
ncollide2d = "0.18.2"
